### ISSUE TITLE
error compiling on MinGW

### ISSUE THREAD

**Issue by TheEditor** [risoflora/libsagui#20]
Compiling W7/64-bit MinGW I get the following:

![image](https://user-images.githubusercontent.com/558011/53385085-3cfc2a00-394b-11e9-80a3-878249ef40ab.png)

My CMake:

cmake -G "MSYS Makefiles" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./output ..
make sagui install/strip

**Comment by silvioprog** [comment]
Confirmed. It will be fixed in next commit. Thanks for reporting! :smiley: :+1:
