### ISSUE TITLE
Fedora build is failing

### ISSUE THREAD

**Issue by frbaroni** [risoflora/libsagui#32]
Thank you for submitting an issue to libSagui!

**Describe the bug**

When I try to build on Fedora, it fails while trying to compile the MHD dependency.

**Steps to reproduce the bug**

1. `mkdir build && cd build`
2. `cmake  ...`
2. `make`
3. Error happened

**Expected behavior**

Clean build works out of box

**Environment:**

 - OS: Fedora Workstation 30
 - Compiler gcc
 - Version master

**Additional context**

Thanks for the great work on this lib!!

**Comment by silvioprog** [comment]
Hello @frbaroni , thanks for reporting and the words! :-)

(Fixed in https://github.com/risoflora/libsagui/commit/6b1d7aa307fa1c6521a6241ec19f40e72cd31c75)
