### ISSUE TITLE
libsagui 3.0.0 required

### ISSUE THREAD

**Issue by Al-Muhandis** [risoflora/libsagui#44]
`May 01 01:53:18 ... .... ...: ESgLibNotLoaded: Library 'libsagui.so.3' not loaded. If it is not available on the system, please download it at: https://github.com/risoflora/libsagui/releases`
Can You release 3.0.0 zip archive? Or should I roll back the BrookFramework  in to the old commit month earlier?

**Comment by Al-Muhandis** [comment]
Previously I rolled back to the commit of a week ago

**Comment by silvioprog** [comment]
Hi @Al-Muhandis. We are going to release Sagui 3.0.0 today. :-)

**Comment by silvioprog** [comment]
Released at https://github.com/risoflora/libsagui/releases/tag/v3.0.0.
