### ISSUE TITLE
MSYS2 build  error

### ISSUE THREAD

**Issue by marklove5102** [risoflora/libsagui#45]
make sagui
Scanning dependencies of target pcre2-10.34
[  2%] Creating directories for 'pcre2-10.34'
[  5%] Performing download step (download, verify and extract) for 'pcre2-10.34'
-- pcre2-10.34 download command succeeded.  See also /home/freem/libsagui/build/pcre2-10.34/src/pcre2-10.34-stamp/pcre2-10.34-download-*.log
[  7%] No patch step for 'pcre2-10.34'
[ 10%] No update step for 'pcre2-10.34'
[ 13%] Performing configure step for 'pcre2-10.34'
-- pcre2-10.34 configure command succeeded.  See also /home/freem/libsagui/build/pcre2-10.34/src/pcre2-10.34-stamp/pcre2-10.34-configure-*.log
[ 15%] Performing build step for 'pcre2-10.34'
-- pcre2-10.34 build command succeeded.  See also /home/freem/libsagui/build/pcre2-10.34/src/pcre2-10.34-stamp/pcre2-10.34-build-*.log
[ 18%] Performing install step for 'pcre2-10.34'
-- pcre2-10.34 install command succeeded.  See also /home/freem/libsagui/build/pcre2-10.34/src/pcre2-10.34-stamp/pcre2-10.34-install-*.log
[ 21%] Completed 'pcre2-10.34'
[ 21%] Built target pcre2-10.34
Scanning dependencies of target libmicrohttpd-0.9.70
[ 23%] Creating directories for 'libmicrohttpd-0.9.70'
[ 26%] Performing download step (download, verify and extract) for 'libmicrohttpd-0.9.70'
-- libmicrohttpd-0.9.70 download command succeeded.  See also /home/freem/libsagui/build/libmicrohttpd-0.9.70/src/libmicrohttpd-0.9.70-stamp/libmicrohttpd-0.9.70-download-*.log
[ 28%] No patch step for 'libmicrohttpd-0.9.70'
[ 31%] No update step for 'libmicrohttpd-0.9.70'
[ 34%] Performing configure step for 'libmicrohttpd-0.9.70'
-- libmicrohttpd-0.9.70 configure command succeeded.  See also /home/freem/libsagui/build/libmicrohttpd-0.9.70/src/libmicrohttpd-0.9.70-stamp/libmicrohttpd-0.9.70-configure-*.log
[ 36%] Performing build step for 'libmicrohttpd-0.9.70'
-- libmicrohttpd-0.9.70 build command succeeded.  See also /home/freem/libsagui/build/libmicrohttpd-0.9.70/src/libmicrohttpd-0.9.70-stamp/libmicrohttpd-0.9.70-build-*.log
[ 39%] Performing install step for 'libmicrohttpd-0.9.70'
-- libmicrohttpd-0.9.70 install command succeeded.  See also /home/freem/libsagui/build/libmicrohttpd-0.9.70/src/libmicrohttpd-0.9.70-stamp/libmicrohttpd-0.9.70-install-*.log
[ 42%] Completed 'libmicrohttpd-0.9.70'
[ 42%] Built target libmicrohttpd-0.9.70
Scanning dependencies of target zlib-1.2.11
[ 44%] Creating directories for 'zlib-1.2.11'
[ 47%] Performing download step (download, verify and extract) for 'zlib-1.2.11'
-- zlib-1.2.11 download command succeeded.  See also /home/freem/libsagui/build/zlib-1.2.11/src/zlib-1.2.11-stamp/zlib-1.2.11-download-*.log
[ 50%] No patch step for 'zlib-1.2.11'
[ 52%] No update step for 'zlib-1.2.11'
[ 55%] Performing configure step for 'zlib-1.2.11'
-- zlib-1.2.11 configure command succeeded.  See also /home/freem/libsagui/build/zlib-1.2.11/src/zlib-1.2.11-stamp/zlib-1.2.11-configure-*.log
[ 57%] Performing build step for 'zlib-1.2.11'
CMake Error at /home/freem/libsagui/build/zlib-1.2.11/src/zlib-1.2.11-stamp/zlib-1.2.11-build-Release.cmake:49 (message):
  Command failed: 2

   'make'

  See also

    /home/freem/libsagui/build/zlib-1.2.11/src/zlib-1.2.11-stamp/zlib-1.2.11-build-*.log

make[3]: *** [CMakeFiles/zlib-1.2.11.dir/build.make:133：zlib-1.2.11/src/zlib-1.2.11-stamp/zlib-1.2.11-build] error 1
make[2]: *** [CMakeFiles/Makefile2:248：CMakeFiles/zlib-1.2.11.dir/all] error 2
make[1]: *** [CMakeFiles/Makefile2:338：src/CMakeFiles/sagui.dir/rule] error 2
make: *** [Makefile:271：sagui] error 2

Msys2：
pacman -Ss zlib
msys/zlib 1.2.11-1 (libraries) [already installed]
    Compression library implementing the deflate compression method found in gzip and PKZIP
msys/zlib-devel 1.2.11-1 (development) [already installed]
    zlib headers and libraries

**Comment by silvioprog** [comment]
Hi @marklove5102. Could you inform the OS and the full steps (including the cmake line) you used before performing `make sagui`? Thank you!

**Comment by marklove5102** [comment]
ok  is open
https://github.com/risoflora/libsagui/blob/master/docs/INSTALL.md#mingw-w64-i686-and-x86_64-on-windows-or-any-supported-os
run：
 cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw32 ..




make[3]: *** [CMakeFiles/zlib-1.2.11.dir/build.make:133：zlib-1.2.11/src/zlib-1.2.11-stamp/zlib-1.2.11-build] error 1
make[2]: *** [CMakeFiles/Makefile2:248：CMakeFiles/zlib-1.2.11.dir/all] error 2
make[1]: *** [CMakeFiles/Makefile2:338：src/CMakeFiles/sagui.dir/rule] error 2
make: *** [Makefile:271：sagui] error 2

**Comment by marklove5102** [comment]
MSYS2  update now
pacman -S mingw-w64-x86_64-gcc
pacman -Syu
pacman -S --needed curl base-devel    mingw-w64-x86_64-toolchain    mingw-w64-x86_64-cmake


build 
cmake -G"MinGW Makefiles" -DMINGW64=ON -DCMAKE_TOOLCHAIN_FILE="../cmake/Toolchain-mingw32-Linux.cmake" ..
-- The C compiler identification is GNU 10.1.0
-- Check for working C compiler: C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc.exe - broken
CMake Error at C:/msys64/mingw64/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/msys64/home/freem/web/libsagui/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/msys64/mingw64/bin/mingw32-make.exe cmTC_2b0da/fast && C:/msys64/mingw64/bin/mingw32-make.exe  -f CMakeFiles\cmTC_2b0da.dir\build.make CMakeFiles/cmTC_2b0da.dir/build
    mingw32-make[1]: Entering directory 'C:/msys64/home/freem/web/libsagui/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_2b0da.dir/testCCompiler.c.obj
    C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe    -o CMakeFiles\cmTC_2b0da.dir\testCCompiler.c.obj   -c C:\msys64\home\freem\web\libsagui\build\CMakeFiles\CMakeTmp\testCCompiler.c
    Linking C executable cmTC_2b0da.exe
    C:\msys64\mingw64\bin\cmake.exe -E cmake_link_script CMakeFiles\cmTC_2b0da.dir\link.txt --verbose=1
    C:\msys64\mingw64\bin\cmake.exe -E rm -f CMakeFiles\cmTC_2b0da.dir/objects.a
    CMAKE_AR-NOTFOUND cr CMakeFiles\cmTC_2b0da.dir/objects.a @CMakeFiles\cmTC_2b0da.dir\objects1.rsp
    Error running link command: 缁崵绮洪幍鍙ョ瑝閸掔増瀵氱€规氨娈戦弬鍥︽閵?mingw32-make[1]: *** [CMakeFiles\cmTC_2b0da.dir\build.make:108: cmTC_2b0da.exe] Error 2
    mingw32-make[1]: Leaving directory 'C:/msys64/home/freem/web/libsagui/build/CMakeFiles/CMakeTmp'
    mingw32-make: *** [Makefile:140: cmTC_2b0da/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:43 (project)


-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/freem/web/libsagui/build/CMakeFiles/CMakeOutput.log".
See also "C:/msys64/home/freem/web/libsagui/build/CMakeFiles/CMakeError.log".

**Comment by marklove5102** [comment]
When I update cmake to leave the Chinese Directory build

No more problems
