### ISSUE TITLE
How to handle POST?

### ISSUE THREAD

**Issue by stensalweb** [risoflora/libsagui#51]
This library is neat, and I love the use of pcre2 to do routing.   I have looked at all examples but cannot find one for handling the form posting.  Is it possible to extract the  key/value pairs from a post?

**Comment by silvioprog** [comment]
Hey @stensalweb, I'm glad you liked Sagui and you would love to use its routing! 🙂

You are right. It seems we don't have any example showing how to handle forms. I'm going to provide one ...

**Comment by silvioprog** [comment]
@stensalweb Done. :+1: 

Using cURL to simulate a form sending: [example_httpreq_form.c#L30](https://github.com/risoflora/libsagui/blob/master/examples/example_httpreq_form.c#L30).
Intercepting the form fields: [example_httpreq_form.c#L43](https://github.com/risoflora/libsagui/blob/master/examples/example_httpreq_form.c#L43).

Thanks a lot!

**Comment by stensalweb** [comment]
Thank you so much for such a quick response.
